mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    path('usuarios/', include('usuario.urls')),
    #falta implementar el estado activo e inactivo al momento de "eliminación de un usuario" para no perder el historial del usuario
    # path('estadouser/', include('estadouser.urls')),
    path('proyectos/', include('proyecto.urls')),
    path('roles/', include('rol.urls')),
    path('asignar/', include('proyectousuario.urls')),
    path('sprint/', include('sprint.urls')),
    path('estadouserstory/', include('estadouserstory.urls')),
    path('userstory/', include('userstory.urls')),
]

proyecto/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'proyecto'

urlpatterns = [
    path('', views.lista_proyectos, name='listaproyectos'),
    path('crearproyecto', views.crear_proyecto, name='crearproyecto'),
    path('actualizarproyecto/<int:pk>', views.actualizar_proyecto, name='actualizarproyecto'),
    path('eliminarproyecto/<int:pk>', views.eliminar_proyecto, name='eliminarproyecto'),
]

proyectousuario/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'proyectousuario'

urlpatterns = [
    path('', views.lista_proyectousuarios, name='listaproyectousuarios'),
    path('crearproyectousuario', views.crear_proyectousuario, name='crearproyectousuario'),
    path('actualizarproyectousuario/<int:pk>', views.actualizar_proyectousuario, name='actualizarproyectousuario'),
    path('eliminarproyectousuario/<int:pk>', views.eliminar_proyectousuario, name='eliminarproyectousuario'),
]

rol/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'rol'

urlpatterns = [
    path('', views.lista_roles, name='listaroles'),
    path('crearrol', views.crear_rol, name='crearrol'),
    path('actualizarrol/<int:pk>', views.actualizar_rol, name='actualizarrol'),
    path('eliminarrol/<int:pk>', views.eliminar_rol, name='eliminarrol'),
]

proyectousuario/models.py
from django.db import models
from usuario.models import Usuarios
from proyecto.models import Proyectos
from rol.models import Roles

# Create your models here.

class ProyectoUsuario(models.Model):
    id_proyecto_usuario = models.IntegerField(primary_key=True)
    id_proyecto = models.ForeignKey(Proyectos, on_delete=models.CASCADE)
    id_usuario = models.ForeignKey(Usuarios, on_delete=models.CASCADE)
    id_rol = models.ForeignKey(Roles, on_delete=models.CASCADE)

    class Meta:
        db_table = 'usuario_proyecto'
        verbose_name_plural = 'proyectousuarios'
        verbose_name = 'proyectousuario'

    def __str__(self):
        texto = self.id_usuario.nombre_usuario + " (" + self.id_rol.descripcion_rol + ")"
        return texto

proyectousuario/forms.py
from django import forms
from .models import Usuarios, Proyectos, Roles, ProyectoUsuario

class ProyectoUsuarioForm(forms.ModelForm):
    class Meta:
        model = ProyectoUsuario
        fields = ['id_proyecto_usuario', 'id_proyecto', 'id_usuario', 'id_rol']

proyectousuario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import ProyectoUsuario
from .forms import ProyectoUsuarioForm

# Create your views here.

def lista_proyectousuarios(request):
    proyectousuarios = ProyectoUsuario.objects.all().order_by('id_proyecto_usuario')
    return render(request, 'lista_proyectousuarios.html', {'proyectousuarios': proyectousuarios})


# def usuarios_detail(request, pk):
#     usuario = get_object_or_404(Usuarios, pk=pk)
#     return render(request, 'usuarios/usuarios_detail.html', {'usuario': usuario})


def crear_proyectousuario(request):
    if request.method == "POST":
        form = ProyectoUsuarioForm(request.POST)
        if form.is_valid():
            proyectousuario = form.save(commit=False)
            proyectousuario.save()
            return redirect('proyectousuario:listaproyectousuarios')
    else:
        form = ProyectoUsuarioForm()
    return render(request, 'crear_proyectousuario.html', {'form': form})


def actualizar_proyectousuario(request, pk):
    proyectousuario = get_object_or_404(ProyectoUsuario, pk=pk)
    if request.method == "POST":
        form = ProyectoUsuarioForm(request.POST, instance=proyectousuario)
        if form.is_valid():
            proyectousuario = form.save(commit=False)
            proyectousuario.save()
            return redirect('proyectousuario:listaproyectousuarios')
    else:
        form = ProyectoUsuarioForm(instance=proyectousuario)
    return render(request, 'actualizar_proyectousuario.html', {'form': form})


def eliminar_proyectousuario(request, pk):
    print(request, pk)
    proyectousuario = get_object_or_404(ProyectoUsuario, pk=pk)
    proyectousuario.delete()
    return redirect('proyectousuario:listaproyectousuarios')

proyectousuario/templates/actualizar_proyectousuario.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="col-lg-6">
    <h1 class="text-center">Editar Proyecto-Usuario</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-success" type="submit" value="Actualizar"></button>
    </form>
  </div>
</div>
{% endblock %}

proyectousuario/templates/crear_proyectousuario.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="col-lg-6">
    <h1 class="text-center">Nuevo Proyecto-Usuario</h1>
    <form method="post" action="{% url 'proyectousuario:crearproyectousuario' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-success" type="submit" value="Guardar"></button>
    </form>
  </div>
</div>
{% endblock %}

proyectousuario/templates/lista_proyectousuarios.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>Lista de Proyectos-Usuarios</h1>
    <div>
        <a href="{% url 'proyectousuario:crearproyectousuario' %}" class="btn btn-primary">Asignar Proyecto-Usuario</a>
        <a href="{% url 'proyecto:listaproyectos' %}" class="btn btn-info"><i class="fa fa-arrow-left"></i> Atrás</a>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>ID del Proyecto</th>
            <th>ID del Usuario</th>
            <th>ID del Rol</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody class="table-light">
        {% for proyectousuario in proyectousuarios %}
        <tr>
            <td>{{ proyectousuario.id_proyecto_usuario }}</td>
            <td>{{ proyectousuario.id_proyecto }}</td>
            <td>{{ proyectousuario.id_usuario }}</td>
            <td>{{ proyectousuario.id_rol }}</td>
            <td>
                <!-- <a href="#">Detail</a> | | -->
                <a href="{% url 'proyectousuario:actualizarproyectousuario' proyectousuario.id_proyecto_usuario %}"
                    class="btn btn-secondary">Editar</a>
                <a href="{% url 'proyectousuario:eliminarproyectousuario' proyectousuario.id_proyecto_usuario %}"
                    class="btn btn-danger"
                    onclick="return confirm('¿Estás seguro de que quieres eliminar la asignación de \'{{ proyectousuario.id_usuario }}\'? del proyecto')">Eliminar</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No hay asginaciones de proyectos a usuarios.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- <a href="{% url 'proyectousuario:crearproyectousuario' %}" class="btn btn-primary">Asignar Proyecto-Usuario</a>
<div>
    <a href="{% url 'proyecto:listaproyectos' %}" class="btn btn-info"><i class="fa fa-arrow-left"></i> Atrás</a>
</div> -->
{% endblock %}