menu/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', Login.as_view(), name='login'),
    path('logout', Logout.as_view(), name='logout'),
    path('main', Main.as_view(), name='main'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    path('usuarios/', include('usuario.urls')),
    #falta implementar el estado activo e inactivo al momento de "eliminación de un usuario" para no perder el historial del usuario
    # path('estadouser/', include('estadouser.urls')),
    path('proyectos/', include('proyecto.urls')),
    path('roles/', include('rol.urls')),
    path('asignar/', include('proyectousuario.urls')),
    path('sprint/', include('sprint.urls')),
    path('estadouserstory/', include('estadouserstory.urls')),
    path('userstory/', include('userstory.urls')),
]

proyecto/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'proyecto'

urlpatterns = [
    path('', views.lista_proyectos, name='listaproyectos'),
    path('crearproyecto', views.crear_proyecto, name='crearproyecto'),
    path('actualizarproyecto/<int:pk>', views.actualizar_proyecto, name='actualizarproyecto'),
    path('eliminarproyecto/<int:pk>', views.eliminar_proyecto, name='eliminarproyecto'),
]

rol/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'rol'

urlpatterns = [
    path('', views.lista_roles, name='listaroles'),
    path('crearrol', views.crear_rol, name='crearrol'),
    path('actualizarrol/<int:pk>', views.actualizar_rol, name='actualizarrol'),
    path('eliminarrol/<int:pk>', views.eliminar_rol, name='eliminarrol'),
]

sprint/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'sprint'

urlpatterns = [
    path('', views.lista_sprints, name='listasprints'),
    path('crearsprint', views.crear_sprint, name='crearsprint'),
    path('actualizarsprint/<int:pk>', views.actualizar_sprint, name='actualizarsprint'),
    path('eliminarsprint/<int:pk>', views.eliminar_sprint, name='eliminarsprint'),
]

userstory/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'userstory'

urlpatterns = [
    path('', views.lista_userstories, name='listauserstories'),
    path('crearuserstory', views.crear_userstory, name='crearuserstory'),
    path('actualizaruserstory/<int:pk>', views.actualizar_userstory, name='actualizaruserstory'),
    path('eliminaruserstory/<int:pk>', views.eliminar_userstory, name='eliminaruserstory'),
    path('listasinsprint', views.lista_sinsprint, name='listasinsprint'),
    path('kanbanboard', views.kanban_board, name='kanbanboard'),
    path('burndown/list', views.burndown_list, name='burndownlist'),
    path('burndown/chart/<int:pk>', views.burndown_chart, name='burndownchart'),
]

usuario/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'usuario'

urlpatterns = [
    path('', views.lista_usuarios, name='listausuarios'),
    path('crearusuario', views.crear_usuario, name='crearusuario'),
    path('actualizarusuario/<int:pk>', views.actualizar_usuario, name='actualizarusuario'),
    path('eliminarusuario/<int:pk>', views.eliminar_usuario, name='eliminarusuario'),
]

menu/models.py
from django.db import models

# Create your models here.

menu/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class Login(LoginView):
    next_page = reverse_lazy('main')
    template_name = 'login.html'


class Logout(LogoutView):
    next_page = reverse_lazy('login')


class Main(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('login')
    template_name = 'main.html'

menu/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.108.0">
    <title>Gestión de Proyectos</title>
    <!-- Para el botón de Atrás -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <!-- Bootstrap CSS y Javascript -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
    <!-- Para el tablero kanban -->
    <link rel="stylesheet" href="{% static 'css/kanban.css' %}">

    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom" style="background: white;">
        <span class="fs-4 mx-auto padding-auto">PMO Gestión de Proyectos</span>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <div class="navbar navbar-dark bg-primary" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        <a class="nav-link" href="{% url 'main' %}">Inicio</a>
                        <a class="nav-link" href="{% url 'usuario:listausuarios' %}">Usuarios</a>
                        <a class="nav-link" href="{% url 'proyecto:listaproyectos' %}">Proyectos</a>
                        <a class="nav-link" href="{% url 'sprint:listasprints' %}">Sprint</a>
                        <a class="nav-link" href="{% url 'userstory:kanbanboard' %}">Tablero Kanban</a>
                        <a class="nav-link" href="{% url 'userstory:burndownlist' %}">Burndown Chart</a>
                        <!-- Add the Settings dropdown -->
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="settingsDropdown" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Configuraciones
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="settingsDropdown">
                                <li><a class="dropdown-item" href="{% url 'rol:listaroles' %}">Roles de Usuarios</a>
                                </li>
                                <li><a class="dropdown-item"
                                        href="{% url 'estadouserstory:listaestadouserstories' %}">Estados de un US</a>
                                </li>
                                <!-- <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Separated link</a></li> -->
                            </ul>
                        </li>
                        <a class="nav-link" href="{% url 'logout' %}">Cerrar Sesion</a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</head>
<body>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

menu/templates/login.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestión de Proyectos</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css">
    <style>
        body{
          /* background-color: #f5f5f5; */
          background: #56CCF2;
          /* fallback for old browsers */
          background: -webkit-linear-gradient(to right, #2F80ED, #56CCF2);
          /* Chrome 10-25, Safari 5.1-6 */
          background: linear-gradient(to right, #2F80ED, #56CCF2);
          /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        }
        h1, label {
            color: white;
        }
    </style>
</head>

<body style="margin-top: 9%;margin-bottom: 9%;margin-left: auto;margin-right: auto;">
    <div class="container p-5" style="display: grid; place-items: center;">
        <h1 class="text-center" style="margin-bottom: 5%;">Inicio de sesión</h1>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3 px-5">
                <label for="username" class="form-label">Nombre de Usuario</label>
                <input type="text" name="username" id="username" class="form-control">
                <span class="fs-6 text-danger"></span>
            </div>
            <div class="mb-3 px-5">
                <label for="password" class="form-label">Contraseña</label>
                <input type="text" name="password" id="password" class="form-control">
                <span class="fs-6 text-danger"></span>
            </div>
            <br>
            <div class="d-grid gap-2 col-4 mx-auto">
                <button type="submit" class="btn btn-primary">Ingresar</button>
            </div>
        </form>
    </div>
</body>

</html>

menu/templates/main.html
{% extends 'base.html' %}

{% block content %}

<style>
  body{
    /* background-color: #f5f5f5; */
    background: #56CCF2;
    /* fallback for old browsers */
    background: -webkit-linear-gradient(to right, #2F80ED, #56CCF2);
    /* Chrome 10-25, Safari 5.1-6 */
    background: linear-gradient(to right, #2F80ED, #56CCF2);
    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
  }
	h1{
		color: white;
	}
</style>

<body>
  <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
    <h1 class="display-4 fw-normal">¡Bienvenido!</h1>
    <p class="fs-5" style="color: white;">Herramienta efectiva para el control seguro y confiable de los proyectos en los que se encuentra trabajando.</p>
  </div>
  <div class="row row-cols-1 row-cols-md-3 mb-auto text-center mx-auto">
    <div class="col mx-auto">
      <div class="card mb-4 rounded-3 shadow-sm">
        <div class="card-header py-3">
          <h4 class="my-0 fw-normal">Instrucciones</h4>
        </div>
        <div class="card-body">
          <p class="list-unstyled mt-3 mb-4">Conoce sobre la aplicación</p>
          <button type="button" class="w-100 btn btn-lg btn-outline-primary">
            <a href="{% url 'main' %}">
              Detalles
            </a>
          </button>
        </div>
      </div>
    </div>
  </div>
</body>

{% endblock %}