mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    path('usuarios/', include('usuario.urls')),
    #falta implementar el estado activo e inactivo al momento de "eliminación de un usuario" para no perder el historial del usuario
    # path('estadouser/', include('estadouser.urls')),
    path('proyectos/', include('proyecto.urls')),
    path('roles/', include('rol.urls')),
    path('asignar/', include('proyectousuario.urls')),
    path('sprint/', include('sprint.urls')),
    path('estadouserstory/', include('estadouserstory.urls')),
    path('userstory/', include('userstory.urls')),
]

proyecto/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'proyecto'

urlpatterns = [
    path('', views.lista_proyectos, name='listaproyectos'),
    path('crearproyecto', views.crear_proyecto, name='crearproyecto'),
    path('actualizarproyecto/<int:pk>', views.actualizar_proyecto, name='actualizarproyecto'),
    path('eliminarproyecto/<int:pk>', views.eliminar_proyecto, name='eliminarproyecto'),
]

proyectousuario/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'proyectousuario'

urlpatterns = [
    path('', views.lista_proyectousuarios, name='listaproyectousuarios'),
    path('crearproyectousuario', views.crear_proyectousuario, name='crearproyectousuario'),
    path('actualizarproyectousuario/<int:pk>', views.actualizar_proyectousuario, name='actualizarproyectousuario'),
    path('eliminarproyectousuario/<int:pk>', views.eliminar_proyectousuario, name='eliminarproyectousuario'),
]

rol/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'rol'

urlpatterns = [
    path('', views.lista_roles, name='listaroles'),
    path('crearrol', views.crear_rol, name='crearrol'),
    path('actualizarrol/<int:pk>', views.actualizar_rol, name='actualizarrol'),
    path('eliminarrol/<int:pk>', views.eliminar_rol, name='eliminarrol'),
]

proyecto/models.py
from django.db import models

# Create your models here.

class Proyectos(models.Model):
    id_proyecto = models.IntegerField(primary_key=True)
    nombre_proyecto = models.CharField(max_length=50)

    class Meta:
        db_table = 'proyectos'
        verbose_name_plural = 'proyectos'
        verbose_name = 'proyecto'

    def __str__(self):
        return self.nombre_proyecto

proyecto/forms.py
from django import forms
from .models import Proyectos

class ProyectosForm(forms.ModelForm):
    class Meta:
        model = Proyectos
        fields = ['id_proyecto', 'nombre_proyecto']

proyecto/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Proyectos
from .forms import ProyectosForm

# Create your views here.

def lista_proyectos(request):
    proyectos = Proyectos.objects.all().order_by('id_proyecto')
    return render(request, 'lista_proyectos.html', {'proyectos': proyectos})


# def usuarios_detail(request, pk):
#     usuario = get_object_or_404(Usuarios, pk=pk)
#     return render(request, 'usuarios/usuarios_detail.html', {'usuario': usuario})


def crear_proyecto(request):
    if request.method == "POST":
        form = ProyectosForm(request.POST)
        if form.is_valid():
            proyecto = form.save(commit=False)
            proyecto.save()
            return redirect('proyecto:listaproyectos')
    else:
        form = ProyectosForm()
    return render(request, 'crear_proyecto.html', {'form': form})


def actualizar_proyecto(request, pk):
    proyecto = get_object_or_404(Proyectos, pk=pk)
    if request.method == "POST":
        form = ProyectosForm(request.POST, instance=proyecto)
        if form.is_valid():
            proyecto = form.save(commit=False)
            proyecto.save()
            return redirect('proyecto:listaproyectos')
    else:
        form = ProyectosForm(instance=proyecto)
    return render(request, 'actualizar_proyecto.html', {'form': form})


def eliminar_proyecto(request, pk):
    print(request, pk)
    proyecto = get_object_or_404(Proyectos, pk=pk)
    proyecto.delete()
    return redirect('proyecto:listaproyectos')

proyecto/templates/actualizar_proyecto.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="col-lg-6">
    <h1 class="text-center">Editar Proyecto</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-success" type="submit" value="Actualizar"></button>
    </form>
  </div>
</div>
{% endblock %}

proyecto/templates/crear_proyecto.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="col-lg-6">
    <h1 class="text-center">Nuevo Proyecto</h1>
    <form method="post" action="{% url 'proyecto:crearproyecto' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-success" type="submit" value="Guardar" onclick="alert('Se ha generado automáticamente un Backlog ID para este proyecto')"></button>
    </form>
  </div>
</div>
{% endblock %}

proyecto/templates/lista_proyectos.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>Lista de Proyectos</h1>
    <div>
        <a href="{% url 'proyecto:crearproyecto' %}" class="btn btn-primary">Nuevo Proyecto</a>
        <!-- Botón 'Lista de Proyectos - Usuarios', solo aparece si existen proyectos -->
        {% if proyectos %}
            <a href="{% url 'proyectousuario:listaproyectousuarios' %}" class="btn btn-secondary float-right">Proyectos-Usuarios</a>
        {% endif %}
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre del Proyecto</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody class="table-light">
        {% for proyecto in proyectos %}
        <tr>
            <td>{{ proyecto.id_proyecto }}</td>
            <td>{{ proyecto.nombre_proyecto }}</td>
            <td>
                <!-- <a href="#">Detail</a> | | -->
                <a href="{% url 'proyecto:actualizarproyecto' proyecto.id_proyecto %}"
                    class="btn btn-secondary">Editar</a>
                <a href="{% url 'proyecto:eliminarproyecto' proyecto.id_proyecto %}" class="btn btn-danger"
                    onclick="return confirm('¿Estás seguro de que quieres eliminar el proyecto \'{{ proyecto.nombre_proyecto }}\'?')">Eliminar</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No hay proyectos.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}