mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    path('usuarios/', include('usuario.urls')),
    #falta implementar el estado activo e inactivo al momento de "eliminación de un usuario" para no perder el historial del usuario
    # path('estadouser/', include('estadouser.urls')),
    path('proyectos/', include('proyecto.urls')),
    path('roles/', include('rol.urls')),
    path('asignar/', include('proyectousuario.urls')),
    path('sprint/', include('sprint.urls')),
    path('estadouserstory/', include('estadouserstory.urls')),
    path('userstory/', include('userstory.urls')),
]

rol/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'rol'

urlpatterns = [
    path('', views.lista_roles, name='listaroles'),
    path('crearrol', views.crear_rol, name='crearrol'),
    path('actualizarrol/<int:pk>', views.actualizar_rol, name='actualizarrol'),
    path('eliminarrol/<int:pk>', views.eliminar_rol, name='eliminarrol'),
]

sprint/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'sprint'

urlpatterns = [
    path('', views.lista_sprints, name='listasprints'),
    path('crearsprint', views.crear_sprint, name='crearsprint'),
    path('actualizarsprint/<int:pk>', views.actualizar_sprint, name='actualizarsprint'),
    path('eliminarsprint/<int:pk>', views.eliminar_sprint, name='eliminarsprint'),
]

userstory/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'userstory'

urlpatterns = [
    path('', views.lista_userstories, name='listauserstories'),
    path('crearuserstory', views.crear_userstory, name='crearuserstory'),
    path('actualizaruserstory/<int:pk>', views.actualizar_userstory, name='actualizaruserstory'),
    path('eliminaruserstory/<int:pk>', views.eliminar_userstory, name='eliminaruserstory'),
    path('listasinsprint', views.lista_sinsprint, name='listasinsprint'),
    path('kanbanboard', views.kanban_board, name='kanbanboard'),
    path('burndown/list', views.burndown_list, name='burndownlist'),
    path('burndown/chart/<int:pk>', views.burndown_chart, name='burndownchart'),
]

userstory/models.py
from django.db import models
from datetime import date
from proyectousuario.models import ProyectoUsuario
from estadouserstory.models import EstadosUserStory
from sprint.models import Sprints

# Create your models here.

class UserStory(models.Model):
    id_userstory = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=8000, null=True, blank=True)
    story_point = models.IntegerField(null=True, blank=True)
    definicion_hecho = models.CharField(max_length=8000, null=True, blank=True)
    prioridad = models.IntegerField(null=True, blank=True, default = 1)

    id_estado = models.ForeignKey(EstadosUserStory, on_delete=models.CASCADE, null=True, blank=True)

    fecha_inicio = models.DateField(null=True, blank=True, default = date.today)
    fecha_fin = models.DateField(null=True, blank=True)
    
    id_sprint = models.ForeignKey(Sprints, on_delete=models.CASCADE, null=True, blank=True)
    id_proyectousuario = models.ForeignKey(ProyectoUsuario, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        db_table = 'user_stories'
        verbose_name_plural = 'userstories'
        verbose_name = 'userstory'

    def __str__(self):
        return self.nombre

userstory/forms.py
from django import forms
from .models import UserStory

class UserStoryForm(forms.ModelForm):
    class Meta:
        model = UserStory
        fields = ['id_userstory', 'nombre', 'descripcion', 'story_point', 'definicion_hecho', 'prioridad', 'id_estado', 'fecha_inicio', 'fecha_fin', 'id_sprint', 'id_proyectousuario']

userstory/views.py
from django.shortcuts import render, get_object_or_404
from .models import UserStory
from .forms import UserStoryForm
from sprint.models import Sprints
# Para el Burndown Chart
from django.views import View
from django.db.models import Sum
import plotly #used for plotting
import pandas as pd #used to handle dataframes
import plotly.express as px
import plotly.offline as opy
from datetime import datetime, timedelta


# Create your views here.

def lista_userstories(request):
    userstories = UserStory.objects.all().order_by('id_userstory')
    return render(request, 'lista_userstories.html', {'userstories': userstories})

# def usuarios_detail(request, pk):
#     usuario = get_object_or_404(Usuarios, pk=pk)
#     return render(request, 'usuarios/usuarios_detail.html', {'usuario': usuario})


def crear_userstory(request):
    if request.method == "POST":
        form = UserStoryForm(request.POST)
        if form.is_valid():
            userstory = form.save(commit=False)
            userstory.save()
            userstories = UserStory.objects.all().order_by('id_userstory')
            return render(request, 'lista_userstories.html', {'userstories': userstories})
    else:
        form = UserStoryForm()
    return render(request, 'crear_userstory.html', {'form': form})


def actualizar_userstory(request, pk):
    userstory = get_object_or_404(UserStory, pk=pk)
    if request.method == "POST":
        form = UserStoryForm(request.POST, instance=userstory)
        if form.is_valid():
            userstory = form.save(commit=False)
            userstory.save()
            userstories = UserStory.objects.all().order_by('id_userstory')
            return render(request, 'lista_userstories.html', {'userstories': userstories})
    else:
        form = UserStoryForm(instance=userstory)
    return render(request, 'actualizar_userstory.html', {'form': form})


def eliminar_userstory(request, pk):
    print(request, pk)
    userstory = get_object_or_404(UserStory, pk=pk)
    userstory.delete()
    userstories = UserStory.objects.all().order_by('id_userstory')
    return render(request, 'lista_userstories.html', {'userstories': userstories})


#User Stories sin Sprint

def lista_sinsprint(request):
    userstories = UserStory.objects.filter(id_sprint__isnull=True)
    return render(request, 'lista_sinsprint.html', {'userstories': userstories})


#Tablero Kanban

def kanban_board(request):
    to_do = UserStory.objects.filter(id_estado=1)
    doing = UserStory.objects.filter(id_estado=2)
    done = UserStory.objects.filter(id_estado=3)
    return render(request, 'tablero_kanban.html', {'to_do': to_do, 'doing': doing, 'done': done})


#Burndown Chart

def burndown_list(request):
    sprints = Sprints.objects.all().order_by('id_sprint')
    return render(request, 't_burndown_list.html', {'sprints': sprints})


def burndown_chart(request, pk):
    print(request, pk)
    # extraccion de fechas
    sprint_f_inicio = Sprints.objects.filter(id_sprint=pk).values_list('fecha_inicio', flat=True).first()
    year1 = sprint_f_inicio.year
    month1 = sprint_f_inicio.month
    day1 = sprint_f_inicio.day

    sprint_f_fin = Sprints.objects.filter(id_sprint=pk).values_list('fecha_fin', flat=True).first()
    year2 = sprint_f_fin.year
    month2 = sprint_f_fin.month
    day2 = sprint_f_fin.day

    # Variables de las fechas (extremos del eje x)
    fecha_inicio = datetime(year1, month1, day1)
    fecha_fin = datetime(year2, month2, day2)

    # Calcular puntos intermedios de la fecha de inicio y fin del Sprint
    cantidad_puntos_intermedios = 8
    puntos_intermedios = calcular_puntos_intermedios_fechas(fecha_inicio, fecha_fin, cantidad_puntos_intermedios)

    # Asignar los puntos intermedios hallados a variables distintas
    fecha_intermedia1 = puntos_intermedios[0].strftime('%Y-%m-%d')
    fecha_intermedia2 = puntos_intermedios[1].strftime('%Y-%m-%d')
    fecha_intermedia3 = puntos_intermedios[2].strftime('%Y-%m-%d')
    fecha_intermedia4 = puntos_intermedios[3].strftime('%Y-%m-%d')
    fecha_intermedia5 = puntos_intermedios[4].strftime('%Y-%m-%d')
    fecha_intermedia6 = puntos_intermedios[5].strftime('%Y-%m-%d')
    fecha_intermedia7 = puntos_intermedios[6].strftime('%Y-%m-%d')
    fecha_intermedia8 = puntos_intermedios[7].strftime('%Y-%m-%d')

    # Hallar la totalidad de los Story Point del Sprint
    us = UserStory.objects.filter(id_sprint=pk)
    total_history_points = us.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0

    # filtrando los US por fecha para poder sumar sus story points (f=fecha)
    f1 = UserStory.objects.filter(id_sprint=pk, fecha_fin__lte=fecha_inicio.strftime('%Y-%m-%d'))
    f2 = UserStory.objects.filter(id_sprint=pk, fecha_fin__lte=fecha_intermedia1)
    f3 = UserStory.objects.filter(id_sprint=pk, fecha_fin__lte=fecha_intermedia2)
    f4 = UserStory.objects.filter(id_sprint=pk, fecha_fin__lte=fecha_intermedia3)
    f5 = UserStory.objects.filter(id_sprint=pk, fecha_fin__lte=fecha_intermedia4)
    f6 = UserStory.objects.filter(id_sprint=pk, fecha_fin__lte=fecha_intermedia5)
    f7 = UserStory.objects.filter(id_sprint=pk, fecha_fin__lte=fecha_intermedia6)
    f8 = UserStory.objects.filter(id_sprint=pk, fecha_fin__lte=fecha_intermedia7)
    f9 = UserStory.objects.filter(id_sprint=pk, fecha_fin__lte=fecha_intermedia8)
    f10 = UserStory.objects.filter(id_sprint=pk, fecha_fin__lte=fecha_fin.strftime('%Y-%m-%d'))

    # auxiliar para calcular el story point completados de los US hasta cierta fecha (a=auxiliar, que suma)
    a1 = f1.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0
    a2 = f2.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0
    a3 = f3.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0
    a4 = f4.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0
    a5 = f5.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0
    a6 = f6.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0
    a7 = f7.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0
    a8 = f8.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0
    a9 = f9.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0
    a10 = f10.aggregate(total_points=Sum('story_point')).get('total_points', 0) or 0

    # hallando la "y" del punto p=(x, y). Restando del total, la cantidad de tarea realizada (total - auxiliar)
    py1 = total_history_points - a1
    py2 = total_history_points - a2
    py3 = total_history_points - a3
    py4 = total_history_points - a4
    py5 = total_history_points - a5
    py6 = total_history_points - a6
    py7 = total_history_points - a7
    py8 = total_history_points - a8
    py9 = total_history_points - a9
    py10 = total_history_points - a10

    # hallando los números para formar la trayectoria ideal, que acompañara a los puntos hallados arriba
    numbers = generate_numbers_between(total_history_points, 0)
    numero_intermedio1 = numbers[0]
    numero_intermedio2 = numbers[1]
    numero_intermedio3 = numbers[2]
    numero_intermedio4 = numbers[3]
    numero_intermedio5 = numbers[4]
    numero_intermedio6 = numbers[5]
    numero_intermedio7 = numbers[6]
    numero_intermedio8 = numbers[7]

    # Datos para el gráfico
    dates = [fecha_inicio.strftime('%Y-%m-%d'), fecha_intermedia1, fecha_intermedia2, fecha_intermedia3, fecha_intermedia4, 
             fecha_intermedia5, fecha_intermedia6, fecha_intermedia7, fecha_intermedia8, fecha_fin.strftime('%Y-%m-%d')]
    heights = [py1, py2, py3, py4, py5, py6, py7, py8, py9, py10]
    ideales = [total_history_points, numero_intermedio1, numero_intermedio2, numero_intermedio3, numero_intermedio4,
                numero_intermedio5, numero_intermedio6, numero_intermedio7, numero_intermedio8, 0]

    # Crear DataFrame con los datos
    data = {'Date': dates, 'Story Point': heights, 'Ideal': ideales}

    #Create the pandas DataFrame
    df = pd.DataFrame(data)

    # Convertir la columna 'date' al tipo de dato 'datetime'
    df['Date'] = pd.to_datetime(df['Date'])

    # Crear el gráfico de línea utilizando Plotly Express
    fig = px.line(df, x='Date', y= ['Story Point', 'Ideal'], markers=True, width=1000, height=600)

    # Configuraciones adicionales para el gráfico
    fig.update_traces(textposition="top center", marker_size=10)
    fig.update_layout(title_text='Burndown Chart', title_x=0.5, title_font=dict(size=24))

    chart = opy.plot(fig, auto_open=False, output_type='div')

    return render(request, 't_burndown_chart.html', {'chart': chart})


# Función para calcular los puntos intermedios entre dos fechas
def calcular_puntos_intermedios_fechas(fecha_inicio, fecha_fin, cantidad_puntos):
    delta = (fecha_fin - fecha_inicio) / (cantidad_puntos + 1)
    puntos_intermedios = []
    for i in range(1, cantidad_puntos + 1):
        punto_intermedio = fecha_inicio + delta * i
        puntos_intermedios.append(punto_intermedio)
    return puntos_intermedios


# Función para calcular los números intermedios entre dos números para la trayectoria ideal del gráfico
def generate_numbers_between(start, end):
    # Calcula la diferencia entre los números
    difference = end - start

    # Calcula el espacio entre cada número generado
    interval = difference / 9

    # Genera los 8 números entre los extremos
    numbers = [start + (i * interval) for i in range(1, 9)]

    return numbers

userstory/templates/actualizar_userstory.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="col-lg-6">
    <h1 class="text-center">Editar User Story</h1>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-success" type="submit" value="Actualizar"></button>
    </form>
  </div>
</div>
{% endblock %}

userstory/templates/crear_userstory.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-center">
  <div class="col-lg-6">
    <h1 class="text-center">Nuevo User Story</h1>
    <form method="post" action="{% url 'userstory:crearuserstory' %}">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn btn-success" type="submit" value="Guardar"></button>
    </form>
  </div>
</div>
{% endblock %}

userstory/templates/lista_sinsprint.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>Lista de User Stories sin Sprint</h1>
    <a href="{% url 'userstory:listauserstories' %}" class="btn btn-info"><i class="fa fa-arrow-left"></i> Atrás</a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre del User Story</th>
            <th>Descripción del User Story</th>
            <th>Story Point</th>
            <th>Definición Hecho</th>
            <th>Prioridad</th>
            <th>Estado</th>
            <th>Fecha Inicio</th>
            <th>Fecha Fin</th>
            <th>Sprint</th>
            <th>Asignado</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody class="table-light">
        {% for userstory in userstories %}
        <tr>
            <td>{{ userstory.id_userstory }}</td>
            <td>{{ userstory.nombre }}</td>
            <td>{{ userstory.descripcion }}</td>
            <td>{{ userstory.story_point }}</td>
            <td>{{ userstory.definicion_hecho }}</td>
            <td>{{ userstory.prioridad }}</td>
            <td>{{ userstory.id_estado }}</td>
            <td>{{ userstory.fecha_inicio }}</td>
            <td>{{ userstory.fecha_fin }}</td>
            <td>{{ userstory.id_sprint }}</td>
            <td>{{ userstory.id_proyectousuario }}</td>
            <td>
                <!-- <a href="#">Detail</a> | | -->
                <a href="{% url 'userstory:actualizaruserstory' userstory.id_userstory %}"
                    class="btn btn-secondary">Editar</a>
                <a href="{% url 'userstory:eliminaruserstory' userstory.id_userstory %}" class="btn btn-danger"
                    onclick="return confirm('¿Estás seguro de que quieres eliminar el User Story de \'{{ userstory.id_userstory }}\'?')">Eliminar</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No hay User Story sin Sprint.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- <div>
    <a href="{% url 'userstory:listauserstories' %}" class="btn btn-info"><i class="fa fa-arrow-left"></i> Atrás</a>
</div> -->
{% endblock %}

userstory/templates/lista_userstories.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>Lista de User Stories</h1>

    <div>
        <a href="{% url 'userstory:crearuserstory' %}" class="btn btn-primary">Crear User Story</a>
        <a href="{% url 'userstory:listasinsprint' %}" class="btn btn-warning">User Stories sin Sprint</a>
        <a href="{% url 'sprint:listasprints' %}" class="btn btn-info"><i class="fa fa-arrow-left"></i> Atrás</a>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre del User Story</th>
            <th>Descripción del User Story</th>
            <th>Story Point</th>
            <th>Definición Hecho</th>
            <th>Prioridad</th>
            <th>Estado</th>
            <th>Fecha Inicio</th>
            <th>Fecha Fin</th>
            <th>Sprint</th>
            <th>Asignado</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody class="table-light">
        {% for userstory in userstories %}
        <tr>
            <td>{{ userstory.id_userstory }}</td>
            <td>{{ userstory.nombre }}</td>
            <td>{{ userstory.descripcion }}</td>
            <td>{{ userstory.story_point }}</td>
            <td>{{ userstory.definicion_hecho }}</td>
            <td>{{ userstory.prioridad }}</td>
            <td>{{ userstory.id_estado }}</td>
            <td>{{ userstory.fecha_inicio }}</td>
            <td>{{ userstory.fecha_fin }}</td>
            <td>{{ userstory.id_sprint }}</td>
            <td>{{ userstory.id_proyectousuario }}</td>
            <td>
                <!-- <a href="#">Detail</a> | | -->
                <a href="{% url 'userstory:actualizaruserstory' userstory.id_userstory %}"
                    class="btn btn-secondary">Editar</a>
                <a href="{% url 'userstory:eliminaruserstory' userstory.id_userstory %}" class="btn btn-danger"
                    onclick="return confirm('¿Estás seguro de que quieres eliminar el User Story de \'{{ userstory.id_userstory }}\'?')">Eliminar</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No hay User Story.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<!-- <a href="{% url 'userstory:crearuserstory' %}" class="btn btn-primary">Crear User Story</a>
<div>
    <a href="{% url 'sprint:listasprints' %}" class="btn btn-info"><i class="fa fa-arrow-left"></i> Atrás</a>
</div>
<a href="{% url 'userstory:listasinsprint' %}" class="btn btn-warning">User Stories sin Sprint</a> -->
{% endblock %}

userstory/templates/t_burndown_chart.html
{% extends 'base.html' %}

{% block content %}
<head>
  <div style="display: flex; justify-content: center; align-items: center;">
    {{ chart|safe }}
  </div>
</head>
{% endblock %}

userstory/templates/t_burndown_list.html
{% extends 'base.html' %}

{% block content %}
<div class="d-flex justify-content-between align-items-center mb-3">
    <h1>Burndown Chart</h1>
</div>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre del Sprint</th>
            <th>Nombre del Proyecto</th>
            <th>Fecha de Inicio</th>
            <th>Fecha de Fin Prevista</th>
            <th>Fecha de Fin</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody class="table-light">
        {% for sprint in sprints %}
        <tr>
            <td>{{ sprint.id_sprint }}</td>
            <td>{{ sprint.nombre_sprint }}</td>
            <td>{{ sprint.id_proyecto }}</td>
            <td>{{ sprint.fecha_inicio }}</td>
            <td>{{ sprint.fecha_fin_prev }}</td>
            <td>{{ sprint.fecha_fin }}</td>
            <td>
                <!-- <a href="#" class="btn btn-warning">Burndown Chart</a> -->
                <a href="{% url 'userstory:burndownchart' sprint.id_sprint %}" class="btn btn-warning">Burndown Chart</a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No hay sprints.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

userstory/templates/tablero_kanban.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-4">
        <div class="kanban-column">
            <h2 class="kanban-column-header">To Do</h2>
            {% for user_story in to_do %}
            <div class="kanban-card">{{ user_story.id_userstory }} - {{ user_story.nombre }}</div>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-4">
        <div class="kanban-column">
            <h2 class="kanban-column-header">Doing</h2>
            {% for user_story in doing %}
            <div class="kanban-card">{{ user_story.id_userstory }} - {{ user_story.nombre }}</div>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-4">
        <div class="kanban-column">
            <h2 class="kanban-column-header">Done</h2>
            {% for user_story in done %}
            <div class="kanban-card">{{ user_story.id_userstory }} - {{ user_story.nombre }}</div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}